* Leather Defects Detection (LeaDeD or just leaded) 
This is a computer vision solution for detecting defects in raw leather 
procured by local dealers. The defect detection helps to subjectively assert 
leather's quality and thus its price. 

* Design:
The problem of detecting defects can be compared to 
finding abnormalities/defects in the complex pattern of leather.

Supervised Machine Learning is selected for this job to learn detect these 
abnormalities/defects in complex patterns of leather

Support Vector Machines (SVM) are used as they are known to us and 
well known for their simplicity. Demo will decide the 
feasibility of this design decision. 5 real life input images are 
provided by the customer. 
Out of which 1 is good quality and other are various types of defects.

Feasibility demo will be trained on these 5 images and 
take input of various sub-parts of these images. 
Feasibility demo shall successfully detect the defects as labels (limited to 3 or 4)
Feasibility demo shall also take negative input fetched from web and detect that
they are not leather. 

Major Tasks:
- Labelling facility as requirements
- Training Data Creation using Labelling
- Training of SVM 
- Test Data Creation
- Detection Testing

 
* Journal
** <2018-01-01 Mon> 
*** Training Data Creation
**** labelling data
***** Masking (pomodoros: +++
